package com.example.receiptcareapp.state

/**
 * 2023-01-31
 * pureum
 */
enum class FetchState {
    BAD_INTERNET,PARSE_ERROR,WRONG_CONNECTION,FAIL,SQLITE_CONSTRAINT_PRIMARY_KEY, SOCKET_TIMEOUT_EXCEPTION ,ILLEGAL_STATE_EXCEPTION
}